import type { Metadata } from "next";
import { Inter, EB_Garamond } from "next/font/google";
import "./globals.css";
import { siteTitle } from "./constants";
import client from "@/sanity/sanityClient";
import { Sitemap } from "./types/sitemap";
import Navigation from "@/app/components/Navigation";

const inter = Inter({ subsets: ["latin"] });
const ebGaramond = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-title'
});

export const metadata: Metadata = {
  title: siteTitle,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const sitemapQuery = `*[_type == "sitemap"] {
    title,
    page->,
    icon,
    priority
  } | order(priority asc)`;

  const sitemapData: Sitemap[] = await client.fetch(sitemapQuery);

  return (
    <html lang="en" className={`${inter.className} ${ebGaramond.variable}`}>
      <body className={inter.className}>
        <Navigation sitemapData={sitemapData} siteTitle={siteTitle} />
        {children}
      </body>
    </html>
  );
}
