// app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import { siteTitle } from './constants'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: siteTitle,
  description: 'Generated by create next app',
}

export default function Page() {
  redirect('/home')
}