// app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import { siteTitle } from './constants'
import client from '@/sanity/sanityClient'
import { HeroBlock } from '@/app/components/blocks/HeroBlock'
import { ArticleBlock } from '@/app/components/blocks/ArticleBlock'
import { ContactBlock } from '@/app/components/blocks/ContactBlock'


export const metadata: Metadata = {
  title: siteTitle,
  description: 'Generated by create next app',
}

export default async function Home() {
  const pageQuery = `*[_type == "page" && slug.current == "home"][0] {
    title,
    blocks[] {
      _type,
      _key,
      title,
      subtitle,
      image,
      // ... weitere Felder für andere Block-Typen
    }
  }`;

  const pageData = await client.fetch(pageQuery);

  const renderBlock = (block: any) => {
    switch (block._type) {
      case 'hero':
        return <HeroBlock key={block._key} {...block} />;
      case 'article':
        return <ArticleBlock key={block._key} {...block} />;
      case 'contact':
        return <ContactBlock key={block._key} {...block} />;
      default:
        return null;
    }
  };

  return (
    <main className="min-h-screen bg-gray-50">
      {pageData.blocks?.map(renderBlock)}
    </main>
  );
}